quarkus:
  datasource:
    jdbc:
      url: jdbc:mysql://localhost:3306/meubanco
      username: admin
      password: admin
      driver: com.mysql.cj.jdbc.Driver
  hibernate-orm:
    database:
      generation: create-drop
